In [2]:
from sklearn import tree
# 0 = Smooth 1=Bumpy
X = [[140, 0], [130, 0], [150, 1], [170, 1]]
# 0 = apple 1 = Orange
Y = [0, 0, 1, 1]
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X, Y)

In [3]:
import numpy as np 
import pandas as pd

In [4]:
num_1 = np.array([140,1])

In [7]:
clf.predict([[140,1]])
#Apple

array([0])

In [15]:
# 0 = Smooth 1=Bumpy
X = [[140], [130], [150], [170]]
# 0 = apple 1 = Orange
Y = [0, 0, 1, 1]
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X, Y)

In [16]:
clf.predict([[140]])
#Prediction based on Weight
#Apple

array([0])

In [17]:
X = [[0], [0], [1], [1]]
# 0 = apple 1 = Orange
Y = [0, 0, 1, 1]
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X, Y)

In [18]:
clf.predict([[1]])
#Prediction based on Skin
#Orange

array([1])

In [ ]:
#Using all features is the best way to predict, however, weight also gave the same answer 

In [19]:
# 0 = M 1= F
X = [[1, 15], [1, 25], [0, 32], [0, 40], [0, 12], [0, 14]]
# 0 = Pokemon Go 1 = WhatsApp 2=SnapChat
Y = [0, 1, 2, 1, 0, 0]
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X, Y)

In [20]:
clf.predict([[0,21]])
#WhatsApp

array([1])

In [21]:
clf.predict([[1,18]])
#PokemonGo

array([0])